//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.19 at 03:15:33 PM CEST 
//


package xmlbeans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="question" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="reponse" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="date_creation" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="libelle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="solution" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                           &lt;attribute name="date_modification" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="intitule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ponderation" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="categorie" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="date_creation" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="titre" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "question"
})
@XmlRootElement(name = "questionnaire")
public class Questionnaire {

    protected List<Questionnaire.Question> question;
    @XmlAttribute
    protected String categorie;
    @XmlAttribute(name = "date_creation")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateCreation;
    @XmlAttribute
    protected String titre;
    @XmlAttribute
    protected Byte version;

    /**
     * Gets the value of the question property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the question property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Questionnaire.Question }
     * 
     * 
     */
    public List<Questionnaire.Question> getQuestion() {
        if (question == null) {
            question = new ArrayList<Questionnaire.Question>();
        }
        return this.question;
    }

    /**
     * Gets the value of the categorie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategorie() {
        return categorie;
    }

    /**
     * Sets the value of the categorie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategorie(String value) {
        this.categorie = value;
    }

    /**
     * Gets the value of the dateCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreation() {
        return dateCreation;
    }

    /**
     * Sets the value of the dateCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreation(XMLGregorianCalendar value) {
        this.dateCreation = value;
    }

    /**
     * Gets the value of the titre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitre() {
        return titre;
    }

    /**
     * Sets the value of the titre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitre(String value) {
        this.titre = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setVersion(Byte value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="reponse" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="date_creation" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="libelle" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="solution" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *                 &lt;attribute name="date_modification" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="intitule" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ponderation" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reponse"
    })
    public static class Question {

        protected List<Questionnaire.Question.Reponse> reponse;
        @XmlAttribute
        protected String intitule;
        @XmlAttribute
        protected Byte ponderation;
        @XmlAttribute
        protected Byte version;

        /**
         * Gets the value of the reponse property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reponse property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReponse().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Questionnaire.Question.Reponse }
         * 
         * 
         */
        public List<Questionnaire.Question.Reponse> getReponse() {
            if (reponse == null) {
                reponse = new ArrayList<Questionnaire.Question.Reponse>();
            }
            return this.reponse;
        }

        /**
         * Gets the value of the intitule property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIntitule() {
            return intitule;
        }

        /**
         * Sets the value of the intitule property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIntitule(String value) {
            this.intitule = value;
        }

        /**
         * Gets the value of the ponderation property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getPonderation() {
            return ponderation;
        }

        /**
         * Sets the value of the ponderation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setPonderation(Byte value) {
            this.ponderation = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setVersion(Byte value) {
            this.version = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="date_creation" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="libelle" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="solution" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *       &lt;attribute name="date_modification" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Reponse {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "date_creation")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dateCreation;
            @XmlAttribute
            protected String libelle;
            @XmlAttribute
            protected String solution;
            @XmlAttribute
            protected Byte version;
            @XmlAttribute(name = "date_modification")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar dateModification;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the dateCreation property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDateCreation() {
                return dateCreation;
            }

            /**
             * Sets the value of the dateCreation property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDateCreation(XMLGregorianCalendar value) {
                this.dateCreation = value;
            }

            /**
             * Gets the value of the libelle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLibelle() {
                return libelle;
            }

            /**
             * Sets the value of the libelle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLibelle(String value) {
                this.libelle = value;
            }

            /**
             * Gets the value of the solution property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSolution() {
                return solution;
            }

            /**
             * Sets the value of the solution property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSolution(String value) {
                this.solution = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setVersion(Byte value) {
                this.version = value;
            }

            /**
             * Gets the value of the dateModification property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDateModification() {
                return dateModification;
            }

            /**
             * Sets the value of the dateModification property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDateModification(XMLGregorianCalendar value) {
                this.dateModification = value;
            }

        }

    }

}
